### ISSUE TITLE
NoSuchMethodError in 1.14.4-1.21.2.0 only affects the client

### ISSUE THREAD

**Issue by kreezxil** [TheRandomLabs/RandomPatches#108]
# Client
## crash report
https://pastebin.com/fF1XXehm
## latest log
https://pastebin.com/s3i8DTsU

```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;
	at com.therandomlabs.randompatches.client.WindowIconHandler.readImageToBuffer(WindowIconHandler.java:189) ~[?:1.14.4-1.21.2.0] {re:classloading}
	at com.therandomlabs.randompatches.client.WindowIconHandler.setWindowIcon(WindowIconHandler.java:88) ~[?:1.14.4-1.21.2.0] {re:classloading}
	at com.therandomlabs.randompatches.client.WindowIconHandler.setWindowIcon(WindowIconHandler.java:35) ~[?:1.14.4-1.21.2.0] {re:classloading}
```

**Comment by NielsPilgaard** [comment]
This issue also happens in 1.15.2 :)

**Comment by TheRandomLabs** [comment]
What the hell, that's a standard library method.

**Comment by TheRandomLabs** [comment]
I'm really not sure *how*, but somehow, `java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;` was being called instead of `java.nio.ByteBuffer.rewind()Ljava/nio/Buffer;`. Rebuilding the source code mysteriously fixes this.
**EDIT:** Turns out I was accidentally building with JDK 14. 🤦

**Comment by TheRandomLabs** [comment]
Thanks for reporting this! It wasn't crashing for me for some reason. 😄

**Comment by kreezxil** [comment]
it could be one of those things that doesn't crash in the developer's
environment such as via the IDE but crashes in the field use cases outside
of said environment.
