### ISSUE TITLE
"Failed to transform class : net.minecraft.tileentity.TileEntityPiston"

### ISSUE THREAD

**Issue by xzefir** [TheRandomLabs/RandomPatches#118]
Hello ! I have two errors on my server, but the server does not crash (Version 1.12.2-1.22.1.1) (this is just a bug report) : 

[15:33:44] [main/ERROR] [randompatches]: Failed to transform class: net.minecraft.tileentity.TileEntityPiston
java.lang.NullPointerException: null
	at org.objectweb.asm.tree.InsnList.insert(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at com.therandomlabs.randompatches.patch.TileEntityPistonPatch.patchUpdateSignalFix(TileEntityPistonPatch.java:121) ~[TileEntityPistonPatch.class:?]
	at com.therandomlabs.randompatches.patch.TileEntityPistonPatch.apply(TileEntityPistonPatch.java:30) ~[TileEntityPistonPatch.class:?]
	at com.therandomlabs.randompatches.core.RPTransformer.transform(RPTransformer.java:37) [randompatches-1.12.2-1.22.1.1.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) [ASMTransformerWrapper$TransformerWrapper.class:?]
	at org.spongepowered.asm.service.mojang.LegacyTransformerHandle.transformClassBytes(LegacyTransformerHandle.java:71) [JustEnoughIDs-1.0.3-55.jar:?]
	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.applyTransformers(MixinServiceLaunchWrapper.java:535) [JustEnoughIDs-1.0.3-55.jar:?]
	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassBytes(MixinServiceLaunchWrapper.java:501) [JustEnoughIDs-1.0.3-55.jar:?]
	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassNode(MixinServiceLaunchWrapper.java:579) [JustEnoughIDs-1.0.3-55.jar:?]
	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:1843) [JustEnoughIDs-1.0.3-55.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1007) [JustEnoughIDs-1.0.3-55.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:997) [JustEnoughIDs-1.0.3-55.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:885) [JustEnoughIDs-1.0.3-55.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:730) [JustEnoughIDs-1.0.3-55.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:646) [JustEnoughIDs-1.0.3-55.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:515) [JustEnoughIDs-1.0.3-55.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:440) [JustEnoughIDs-1.0.3-55.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:416) [JustEnoughIDs-1.0.3-55.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [JustEnoughIDs-1.0.3-55.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [JustEnoughIDs-1.0.3-55.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [JustEnoughIDs-1.0.3-55.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [JustEnoughIDs-1.0.3-55.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_261]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_261]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_261]
	at java.lang.Class.forName(Unknown Source) [?:1.8.0_261]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [forge-1.12.2-14.23.5.2838.jar:?]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34) [forge-1.12.2-14.23.5.2838.jar:?]

**And**

[15:33:53] [main/ERROR] [randompatches]: Failed to transform class: net.minecraft.tileentity.TileEntityPiston
java.lang.NullPointerException: null
	at org.objectweb.asm.tree.InsnList.insert(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at com.therandomlabs.randompatches.patch.TileEntityPistonPatch.patchUpdateSignalFix(TileEntityPistonPatch.java:121) ~[TileEntityPistonPatch.class:?]
	at com.therandomlabs.randompatches.patch.TileEntityPistonPatch.apply(TileEntityPistonPatch.java:30) ~[TileEntityPistonPatch.class:?]
	at com.therandomlabs.randompatches.core.RPTransformer.transform(RPTransformer.java:37) [randompatches-1.12.2-1.22.1.1.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) [ASMTransformerWrapper$TransformerWrapper.class:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_261]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_261]
	at net.minecraft.block.Block.registerBlocks(Block.java:2378) [aow.class:?]
	at net.minecraft.init.Bootstrap.register(Bootstrap.java:498) [ni.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1470) [MinecraftServer.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [forge-1.12.2-14.23.5.2838.jar:?]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34) [forge-1.12.2-14.23.5.2838.jar:?]

**Comment by TheRandomLabs** [comment]
Can I have a full `debug.log`?

**Comment by xzefir** [comment]
No problem ! I can send this in private ?

**Comment by TheRandomLabs** [comment]
Sure.

**Comment by xzefir** [comment]
where I can send ?

**Comment by TheRandomLabs** [comment]
CurseForge is fine. :)

**Comment by xzefir** [comment]
It' sent !

**Comment by TheRandomLabs** [comment]
Thank you! It was a silly mistake by me.

**Comment by cedral** [comment]
I have exactly this stack trace from a modpack I am trying to run. Does it indicate a problem or can I just ignore it. If it's a problem, at what version did you fix your silly mistake?

**Comment by TheRandomLabs** [comment]
1.12.2-1.22.1.2. It shouldn't cause any problems.
