### ISSUE TITLE
[1.12.2] Unable to place water with buckets after last update.

### ISSUE THREAD

**Issue by ProsperCraft** [TheRandomLabs/RandomPatches#126]
[22:21:29 FATAL]: Error executing task
 java.util.concurrent.ExecutionException: java.lang.IncompatibleClassChangeError: Class net.minecraft.util.EnumFacing does not implement the requested interface net.minecraft.block.state.IBlockState
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_265]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_265]
        at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:843) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:470) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:781) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.IncompatibleClassChangeError: Class net.minecraft.util.EnumFacing does not implement the requested interface net.minecraft.block.state.IBlockState
        at com.therandomlabs.randompatches.hook.ItemBucketHook.isSolid(ItemBucketHook.java:12) ~[ItemBucketHook.class:?]
        at net.minecraft.item.ItemBucket.tryPlaceContainedLiquid(ItemBucket.java:207) ~[ahi.class:?]
        at net.minecraft.item.ItemBucket.onItemRightClick(ItemBucket.java:116) ~[ahi.class:?]
        at net.minecraft.item.ItemStack.useItemRightClick(ItemStack.java:237) ~[aip.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.processRightClick(PlayerInteractionManager.java:440) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.processTryUseItem(NetHandlerPlayServer.java:1212) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.processPacket(CPacketPlayerTryUseItem.java:36) ~[mb.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.processPacket(CPacketPlayerTryUseItem.java:9) ~[mb.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_265]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_265]
        at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
        ... 5 more

**Comment by TheRandomLabs** [comment]
Just to confirm, you're on 1.12.2-1.22.1.6? Could I have a debug.log?

**Comment by TheRandomLabs** [comment]
My bad. See if the latest release fixes this. 😄

**Comment by ProsperCraft** [comment]
Fixed now, thank you.
