### ISSUE TITLE
Description: Exception in server tick loop

### ISSUE THREAD

**Issue by Kreidj** [TheRandomLabs/RandomPatches#127]
Hi, I recently started the server and it started giving such errors. Before that, I started the server and nothing bad happened. Please, help

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 10/20/20 7:36 AM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:611)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:335)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:166)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:602)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.privateGetPublicMethods(Class.java:2917)
	at java.lang.Class.getMethods(Class.java:1615)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:84)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 32 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.util.ITooltipFlag
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 39 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 41 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.19.0-8-amd64
	Java Version: 1.8.0_262, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 487903976 bytes (465 MB) / 758644736 bytes (723 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 1 total; -Xmx8192M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	CraftBukkit Information: 
   Running: 
   Failed to handle CraftCrashReport:
java.lang.NullPointerException
	at org.bukkit.Bukkit.getName(Bukkit.java:92)
	at org.bukkit.craftbukkit.v1_12_R1.CraftCrashReport.call(CraftCrashReport.java:20)
	at net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:96)
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:120)
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:41)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:665)
	at java.lang.Thread.run(Thread.java:748)

	FML: MCP 9.42 Powered by Forge 14.23.5.2847 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version          | Source                                     | Signature |
	|:----- |:------------------ |:---------------- |:------------------------------------------ |:--------- |
	| LC    | minecraft          | 1.12.2           | minecraft.jar                              | None      |
	| LC    | mcp                | 9.42             | minecraft.jar                              | None      |
	| LC    | FML                | 8.0.99.99        | CatServer-3440193-universal.jar            | None      |
	| LC    | forge              | 14.23.5.2847     | CatServer-3440193-universal.jar            | None      |
	| LC    | guideapi           | 1.12-2.1.8-63    | Guide-API-1.12-2.1.8-63.jar                | None      |
	| LC    | bloodmagic         | 1.12.2-2.4.3-105 | BloodMagic-1.12.2-2.4.3-105.jar            | None      |
	| LC    | animus             | 1                | Animus-1.12-2.1.7.jar                      | None      |
	| LE    | baubles            | 1.5.2            | Baubles-1.12-1.5.2.jar                     | None      |
	| L     | thaumcraft         | 6.1.BETA26       | Thaumcraft-1.12.2-6.1.BETA26.jar           | None      |
	| L     | arcanearteries     | 0.0.1 - Beta     | ArcaneArteries-1.12.2-1.0.0.jar            | None      |
	| L     | bloodarsenal       | 1.12.2-2.2.2-31  | BloodArsenal-1.12.2-2.2.2-31.jar           | None      |
	| L     | crimsonrevelations | 0.8              | crimsonrevelations-0.8.jar                 | None      |
	| L     | embers             | 1.14-hotfix      | EmbersRekindled-1.14-hotfix.jar            | None      |
	| L     | jei                | 4.16.1.301       | jei_1.12.2-4.16.1.301.jar                  | None      |
	| L     | jojobadv           | 1.1.2            | JojoBAdv-1.1.2+-+12.2.2.jar                | None      |
	| L     | placebo            | 1.6.0            | Placebo-1.12.2-1.6.0.jar                   | None      |
	| L     | tcinventoryscan    | 2.0.10           | ThaumicInventoryScanning_1.12.2-2.0.10.jar | None      |
	| L     | thaumicperiphery   | 0.3.1            | thaumicperiphery-0.3.1.jar                 | None      |
	| L     | vampirism          | 1.6.2            | Vampirism-1.12.2-1.6.2.jar                 | None      |
	| L     | teamlapen-lib      | 1.6.2            | Vampirism-1.12.2-1.6.2.jar                 | None      |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
(sry for bad english)

**Comment by TheRandomLabs** [comment]
Does the issue persist without RandomPatches? This doesn't look like it's related to my mod.

**Comment by TheRandomLabs** [comment]
Let me know if this is still a problem. :smile:
