### ISSUE TITLE
Cannot join Roguelike Dungeons and Dragons server: Failed to transform class: net.minecraft.network.NettyCompressionDecoder java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by tankirules** [TheRandomLabs/RandomPatches#129]
This ends up timing me out when I try to join. I am posting it here because it seems to be caused by random patches in the error message.
Failed to transform class: net.minecraft.network.NettyCompressionDecoder
java.lang.NullPointerException: null
	at org.objectweb.asm.tree.InsnList.insert(InsnList.java:347) ~[asm-debug-all-5.2.jar:5.2]
	at com.therandomlabs.randompatches.patch.packetsize.NettyCompressionDecoderPatch.apply(NettyCompressionDecoderPatch.java:41) ~[NettyCompressionDecoderPatch.class:?]
	at com.therandomlabs.randompatches.core.RPTransformer.transform(RPTransformer.java:37) [randompatches-1.12.2-1.22.0.0.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) [ASMTransformerWrapper$TransformerWrapper.class:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]

[debug.log](https://github.com/TheRandomLabs/RandomPatches/files/5544817/debug.log)

**Comment by TheRandomLabs** [comment]
You have Bigger Packets Please installed, which is redundant, as RandomPatches implements the same fix.
