### ISSUE TITLE
[1.16.4] Error occurred applying transform of coremod patches/ServerPlayNetHandler.js function RandomPatches ServerPlayNetHandler Transformer

### ISSUE THREAD

**Issue by PapiOphidian** [TheRandomLabs/RandomPatches#137]
Non fatal error message on first player login (1 time only).

Env:
server software - [MohistMC](https://github.com/Mohist-Community/Mohist)
other mods installed - AI Improvements, Nether Portal Fix
RandomPatches version: 1.16.4-1.22.1.9 (latest as of issue creation)

Java:
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)

Stack:
[RandomPatches ServerLoginNetHandler Transformer]: Patching method: func_73660_a (func_73660_a)
[RandomPatches ServerPlayNetHandler Transformer]: Patching method: func_73660_a (func_73660_a)
[14:36:12 ERROR]: Error occurred applying transform of coremod patches/ServerPlayNetHandler.js function RandomPatches ServerPlayNetHandler Transformer
java.lang.RuntimeException: java.lang.NoSuchMethodException: None of the fixed arity signatures [(org.objectweb.asm.tree.AbstractInsnNode, org.objectweb.asm.
tree.AbstractInsnNode), (org.objectweb.asm.tree.AbstractInsnNode, org.objectweb.asm.tree.InsnList)] of method org.objectweb.asm.tree.InsnList.insert match th
e argument types [jdk.nashorn.internal.runtime.Undefined, org.objectweb.asm.tree.FieldInsnNode]
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:397) ~[nashorn.jar:?] {}
        at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:117) ~[nashorn.jar:?] {}
        at net.minecraftforge.coremod.transformer.CoreModClassTransformer.runCoremod(CoreModClassTransformer.java:18) ~[coremods-3.0.0.jar:?] {}
        at net.minecraftforge.coremod.transformer.CoreModClassTransformer.runCoremod(CoreModClassTransformer.java:10) ~[coremods-3.0.0.jar:?] {}
        at net.minecraftforge.coremod.transformer.CoreModBaseTransformer.transform(CoreModBaseTransformer.java:38) ~[coremods-3.0.0.jar:?] {}
        at cpw.mods.modlauncher.TransformerHolder.transform(TransformerHolder.java:41) ~[modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.performVote(ClassTransformer.java:179) ~[modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:116) ~[modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.6.jar:?] {re:classloading}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.6.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275] {}
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:237) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:141) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1167) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:
A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:352) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1048) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:
A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:881) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner
:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:268) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistc
leaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275] {}
Caused by: java.lang.NoSuchMethodException: None of the fixed arity signatures [(org.objectweb.asm.tree.AbstractInsnNode, org.objectweb.asm.tree.AbstractInsn
Node), (org.objectweb.asm.tree.AbstractInsnNode, org.objectweb.asm.tree.InsnList)] of method org.objectweb.asm.tree.InsnList.insert match the argument types
[jdk.nashorn.internal.runtime.Undefined, org.objectweb.asm.tree.FieldInsnNode]
        at jdk.internal.dynalink.beans.OverloadedMethod.throwNoSuchMethod(OverloadedMethod.java:202) ~[nashorn.jar:?] {}
        at jdk.nashorn.internal.scripts.Script$Recompilation$89$2817A$\^eval\_.patchTick(<eval>:134) ~[?:?] {re:classloading}
        at jdk.nashorn.internal.scripts.Script$Recompilation$87$1029AAA$\^eval\_.patch(<eval>:31) ~[?:?] {re:classloading}
        at jdk.nashorn.internal.scripts.Script$Recompilation$86$1448A$\^eval\_.initializeCoreMod#transformer(<eval>:52) ~[?:?] {re:classloading}
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:639) ~[nashorn.jar:?] {}
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494) ~[nashorn.jar:?] {}
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393) ~[nashorn.jar:?] {}
        ... 19 more
[14:36:13 INFO]: UUID of player PapiOphidian is ...

**Comment by TheRandomLabs** [comment]
MohistMC compatibility should be fixed in the next release. :smile:
