### ISSUE TITLE
Incompatibility with Performant

### ISSUE THREAD

**Issue by BedrockLegends** [TheRandomLabs/RandomPatches#150]
[24Dec2020 22:50:17.514] [pool-3-thread-1/DEBUG] [mixin/]: Mixing item.CompoundNBTMixin from performant.mixins.json into net.minecraft.nbt.CompoundNBT
[24Dec2020 22:50:17.522] [pool-3-thread-1/FATAL] [mixin/]: Mixin apply failed randompatches.mixins.json:CompoundNBTMixin -> net.minecraft.nbt.CompoundNBT: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/nbt/CompoundNBT::areTagMapsEqual with priority 1000 cannot inject into net/minecraft/nbt/CompoundNBT::equals(Ljava/lang/Object;)Z merged by com.performant.coremod.mixin.item.CompoundNBTMixin with priority 1000 [PREINJECT Applicator Phase -> randompatches.mixins.json:CompoundNBTMixin -> Prepare Injections ->  -> redirect$zzc000$areTagMapsEqual(Ljava/lang/Object;Ljava/lang/Object;)Z -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/nbt/CompoundNBT::areTagMapsEqual with priority 1000 cannot inject into net/minecraft/nbt/CompoundNBT::equals(Ljava/lang/Object;)Z merged by com.performant.coremod.mixin.item.CompoundNBTMixin with priority 1000 [PREINJECT Applicator Phase -> randompatches.mixins.json:CompoundNBTMixin -> Prepare Injections ->  -> redirect$zzc000$areTagMapsEqual(Ljava/lang/Object;Ljava/lang/Object;)Z -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.0.6.jar:8.0.6+85+master.325de55]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:119) ~[modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_272]
	at net.minecraft.nbt.JsonToNBT.func_193593_f(SourceFile:149) ~[?:?]
	at net.minecraft.nbt.JsonToNBT.func_193609_a(SourceFile:46) ~[?:?]
	at net.minecraft.nbt.JsonToNBT.func_180713_a(SourceFile:41) ~[?:?]
	at net.minecraft.util.datafix.fixes.BlockStateFlatteningMap.func_210048_b(SourceFile:72) ~[?:?]
	at net.minecraft.util.datafix.fixes.BlockStateFlatteningMap.func_199194_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.datafix.fixes.BlockStateFlatteningMap.<clinit>(SourceFile:89) ~[?:?]
	at net.minecraft.util.datafix.fixes.ChunkPaletteFormat.<clinit>(SourceFile:50) ~[?:?]
	at net.minecraft.util.datafix.DataFixesManager.func_210891_a(SourceFile:349) ~[?:?]
	at net.minecraft.util.datafix.DataFixesManager.func_188279_a(SourceFile:207) ~[?:?]
	at net.minecraft.util.datafix.DataFixesManager.<clinit>(SourceFile:203) ~[?:?]
	at net.minecraft.util.Util.func_240990_b_(SourceFile:200) ~[?:?]
	at net.minecraft.util.Util.func_240976_a_(SourceFile:193) ~[?:?]
	at net.minecraft.entity.EntityType$Builder.func_206830_a(EntityType.java:657) ~[?:?]
	at net.minecraft.entity.EntityType.func_200712_a(EntityType.java:280) ~[?:?]
	at net.minecraft.entity.EntityType.<clinit>(EntityType.java:148) ~[?:?]
	at net.minecraft.world.gen.feature.DungeonsFeature.<clinit>(DungeonsFeature.java:24) ~[?:?]
	at net.minecraft.world.gen.feature.Feature.<clinit>(Feature.java:37) ~[?:?]
	at net.minecraft.world.gen.feature.Features.<clinit>(SourceFile:92) ~[?:?]
	at net.minecraft.util.registry.WorldGenRegistries.lambda$static$2(WorldGenRegistries.java:39) ~[?:?]
	at net.minecraft.util.registry.WorldGenRegistries.lambda$static$6(WorldGenRegistries.java:89) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:1.8.0_272]
	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88) ~[?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464) ~[?:?]
	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38) ~[?:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_272]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_272]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_272]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_272]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
[24Dec2020 22:50:17.547] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[24Dec2020 22:50:17.547] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[24Dec2020 22:50:17.547] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[24Dec2020 22:50:17.547] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[24Dec2020 22:50:17.548] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[24Dec2020 22:50:17.548] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[24Dec2020 22:50:17.548] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[24Dec2020 22:50:17.548] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[24Dec2020 22:50:17.548] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[24Dec2020 22:50:17.548] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[24Dec2020 22:50:17.548] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[24Dec2020 22:50:17.548] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[24Dec2020 22:50:17.548] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[24Dec2020 22:50:17.548] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[24Dec2020 22:50:17.548] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: Caused by: java.lang.RuntimeException: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[24Dec2020 22:50:17.548] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:43)
[24Dec2020 22:50:17.548] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.client.main.Main.main(Main.java:123)
[24Dec2020 22:50:17.548] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	... 10 more
[24Dec2020 22:50:17.549] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[24Dec2020 22:50:17.549] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[24Dec2020 22:50:17.549] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223)
[24Dec2020 22:50:17.549] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121)
[24Dec2020 22:50:17.549] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131)
[24Dec2020 22:50:17.549] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[24Dec2020 22:50:17.549] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[24Dec2020 22:50:17.549] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:119)
[24Dec2020 22:50:17.549] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[24Dec2020 22:50:17.549] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[24Dec2020 22:50:17.549] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[24Dec2020 22:50:17.549] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[24Dec2020 22:50:17.549] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.nbt.JsonToNBT.func_193593_f(SourceFile:149)
[24Dec2020 22:50:17.550] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.nbt.JsonToNBT.func_193609_a(SourceFile:46)
[24Dec2020 22:50:17.550] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.nbt.JsonToNBT.func_180713_a(SourceFile:41)
[24Dec2020 22:50:17.550] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.util.datafix.fixes.BlockStateFlatteningMap.func_210048_b(SourceFile:72)
[24Dec2020 22:50:17.550] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.util.datafix.fixes.BlockStateFlatteningMap.func_199194_a(SourceFile:21)
[24Dec2020 22:50:17.550] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.util.datafix.fixes.BlockStateFlatteningMap.<clinit>(SourceFile:89)
[24Dec2020 22:50:17.550] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.util.datafix.fixes.ChunkPaletteFormat.<clinit>(SourceFile:50)
[24Dec2020 22:50:17.550] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.util.datafix.DataFixesManager.func_210891_a(SourceFile:349)
[24Dec2020 22:50:17.550] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.util.datafix.DataFixesManager.func_188279_a(SourceFile:207)
[24Dec2020 22:50:17.550] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.util.datafix.DataFixesManager.<clinit>(SourceFile:203)
[24Dec2020 22:50:17.550] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.util.Util.func_240990_b_(SourceFile:200)
[24Dec2020 22:50:17.550] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.util.Util.func_240976_a_(SourceFile:193)
[24Dec2020 22:50:17.550] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.entity.EntityType$Builder.func_206830_a(EntityType.java:657)
[24Dec2020 22:50:17.550] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.entity.EntityType.func_200712_a(EntityType.java:280)
[24Dec2020 22:50:17.550] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.entity.EntityType.<clinit>(EntityType.java:148)
[24Dec2020 22:50:17.550] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.world.gen.feature.DungeonsFeature.<clinit>(DungeonsFeature.java:24)
[24Dec2020 22:50:17.550] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.world.gen.feature.Feature.<clinit>(Feature.java:37)
[24Dec2020 22:50:17.550] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.world.gen.feature.Features.<clinit>(SourceFile:92)
[24Dec2020 22:50:17.551] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.util.registry.WorldGenRegistries.lambda$static$2(WorldGenRegistries.java:39)
[24Dec2020 22:50:17.551] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.util.registry.WorldGenRegistries.lambda$static$6(WorldGenRegistries.java:89)
[24Dec2020 22:50:17.551] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
[24Dec2020 22:50:17.551] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88)
[24Dec2020 22:50:17.551] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464)
[24Dec2020 22:50:17.551] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)
[24Dec2020 22:50:17.551] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123)
[24Dec2020 22:50:17.551] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[24Dec2020 22:50:17.551] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[24Dec2020 22:50:17.551] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[24Dec2020 22:50:17.551] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[24Dec2020 22:50:17.551] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at java.lang.Thread.run(Thread.java:748)
[24Dec2020 22:50:17.551] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [randompatches.mixins.json:CompoundNBTMixin] from phase [DEFAULT] in config [randompatches.mixins.json] FAILED during APPLY
[24Dec2020 22:50:17.552] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
[24Dec2020 22:50:17.552] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
[24Dec2020 22:50:17.552] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
[24Dec2020 22:50:17.552] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	... 40 more
[24Dec2020 22:50:17.552] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/nbt/CompoundNBT::areTagMapsEqual with priority 1000 cannot inject into net/minecraft/nbt/CompoundNBT::equals(Ljava/lang/Object;)Z merged by com.performant.coremod.mixin.item.CompoundNBTMixin with priority 1000 [PREINJECT Applicator Phase -> randompatches.mixins.json:CompoundNBTMixin -> Prepare Injections ->  -> redirect$zzc000$areTagMapsEqual(Ljava/lang/Object;Ljava/lang/Object;)Z -> Prepare]
[24Dec2020 22:50:17.552] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
[24Dec2020 22:50:17.552] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
[24Dec2020 22:50:17.552] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375)
[24Dec2020 22:50:17.552] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255)
[24Dec2020 22:50:17.552] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
[24Dec2020 22:50:17.552] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
[24Dec2020 22:50:17.552] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[24Dec2020 22:50:17.552] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[24Dec2020 22:50:17.552] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[24Dec2020 22:50:17.552] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[24Dec2020 22:50:17.552] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	... 40 more
****

**Comment by TheRandomLabs** [comment]
Whoa, that was quick. Thanks for reporting!

**Comment by WenXin20** [comment]
I got the same, most likely because of the mod Performant.
[Crash Report](https://gist.github.com/WenXin20/499ded8b508d2062dd2f08c28949bbd9)

**Comment by TheRandomLabs** [comment]
Yep, Performant is using an `@Overwrite` on `CompoundNBT#equals`, breaking compatibility. For the moment, add `"CompoundNBT"` to `misc.mixinBlacklist`.

**Comment by BugmanBugman** [comment]
Yeah I got this as well. Will do, thx

**Comment by BedrockLegends** [comment]
Fixed in https://www.curseforge.com/minecraft/mc-mods/performant/files/3148917
