### ISSUE TITLE
[1.12.2] NetHandlerPlayServer patch is incompatible with Valkyrien Skies

### ISSUE THREAD

**Issue by shanzenos** [TheRandomLabs/RandomPatches#152]
I keep getting an exception very similar to an issue opened here before:
https://github.com/TheRandomLabs/RandomPatches/issues/63
This crash occurs at complete random even without being interacted with, it happens at random intervals, it could be 5 minutes or 5 days and strangely I am the only user (admin) affected by this issue.
Actual exception:
```
[01:35:17] [main/ERROR] [randompatches]: Failed to transform class: net.minecraft.network.NetHandlerPlayServer
java.lang.NullPointerException: null
	at org.objectweb.asm.tree.InsnList.insert(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at com.therandomlabs.randompatches.patch.NetHandlerPlayServerPatch.patchUpdate(NetHandlerPlayServerPatch.java:121) ~[NetHandlerPlayServerPatch.class:?]
	at com.therandomlabs.randompatches.patch.NetHandlerPlayServerPatch.apply(NetHandlerPlayServerPatch.java:26) ~[NetHandlerPlayServerPatch.class:?]
	at com.therandomlabs.randompatches.core.RPTransformer.transform(RPTransformer.java:37) [Randompatches%20(1.21.0.3).jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:252) [ASMTransformerWrapper$TransformerWrapper.class:1.12.2-726c70f]
	at org.spongepowered.asm.service.mojang.LegacyTransformerHandle.transformClassBytes(LegacyTransformerHandle.java:71) [valkyrien-skies-1.12.2-1.1.0.jar:?]
	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.applyTransformers(MixinServiceLaunchWrapper.java:388) [valkyrien-skies-1.12.2-1.1.0.jar:?]
	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassBytes(MixinServiceLaunchWrapper.java:352) [valkyrien-skies-1.12.2-1.1.0.jar:?]
	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassNode(MixinServiceLaunchWrapper.java:432) [valkyrien-skies-1.12.2-1.1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:1676) [valkyrien-skies-1.12.2-1.1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTarget(MixinInfo.java:908) [valkyrien-skies-1.12.2-1.1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:891) [valkyrien-skies-1.12.2-1.1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) [valkyrien-skies-1.12.2-1.1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) [valkyrien-skies-1.12.2-1.1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) [valkyrien-skies-1.12.2-1.1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:502) [valkyrien-skies-1.12.2-1.1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) [valkyrien-skies-1.12.2-1.1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) [valkyrien-skies-1.12.2-1.1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) [valkyrien-skies-1.12.2-1.1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) [valkyrien-skies-1.12.2-1.1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [valkyrien-skies-1.12.2-1.1.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) [?:1.8.0_265]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_265]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_265]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_265]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:78) [mohist.jar:1.12.2-726c70f]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:42) [mohist.jar:1.12.2-726c70f]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at red.mohist.Mohist.main(Mohist.java:65) [mohist.jar:1.12.2-726c70f]
```

**Comment by TheRandomLabs** [comment]
Please update to the latest 1.12.2 build. :smile:
(If this doesn't solve the issue, let me know.)

**Comment by shanzenos** [comment]
> Please update to the latest 1.12.2 build. 
> (If this doesn't solve the issue, let me know.)
The issue remains on the newest version of randompatches (from dec. 8)

**Comment by TheRandomLabs** [comment]
Dammit. 😛

**Comment by shanzenos** [comment]
Some new info, I don't know if it's directly related to VS, despite what the logs say. The actual crash never seems to show up in the logs, the error above just seems to always immediately proceed it. It ONLY happens to my account, opped or de-opped, I am running mohist as my server software which is a hybrid server solution and known to act a bit odd with many mods. I hadn't updated random patches nor any mod in months however and this has been happening as of a week or two ago, at random intervals. The error I get clientside is a generic:
` Internal Exception: java.IOException: An established connection was aborted by the software in your host machine`  it spits out for all users. There's a good chance the issue is not even related to random patches, it's simply the last thing that always appears in the log. Disabling the randompatches netplay handler does not fix this either.

**Comment by TheRandomLabs** [comment]
If disabling the `NetHandlerPlayServer` patch doesn't resolve it, then you're probably right in that it's not RP's fault.

**Comment by shanzenos** [comment]
The VS incompat definitely is though, good luck with cleaning that up for the logs. I'm glad to see you're so quick to the draw haha.

**Comment by TheRandomLabs** [comment]
I can't reproduce the error with RP and VS.

**Comment by shanzenos** [comment]
All 3 parts right? VS (main), world and control need to be installed with that mod.

**Comment by TheRandomLabs** [comment]
Yeah, it didn't crash for me, and I didn't see any error messages. Did you say you had to wait a while for the error message to show up? If so, that doesn't make any sense... 🤔 
**EDIT:** Can I have a full `debug.log`?

**Comment by Linguardium** [comment]
at red.mohist.Mohist.main(Mohist.java:65) [mohist.jar:1.12.2-726c70f]

does it occur when running a standard forge server rather than a mohist server?
