### ISSUE TITLE
Compatibility issue with NBT crafting, Fabric Zero, and Random Patches

### ISSUE THREAD

**Issue by FewerFlaws** [TheRandomLabs/RandomPatches#158]
**Version**
Minecraft 1.16.4
NBT Crafting 2.0.3
Fabric Zero 0.2.0
Random Patches 2.1.0
MultiMC 0.6.11-1430
Fabric API 0.29.0

**Describe the bug**
Running these three mods alongside each other creates a series of errors related to mixins.  Disabling any one of the mods resolves the issue.  Running all three together spams the log with errors.

**To Reproduce**
1. Start minecraft running only Fabric API and the three mods in question.
2. Watch an Async Class PreLoader warning appear in the log followed by a series of errors.
3. Minecraft will still start.

**Expected behavior**
The game should start without errors in the log.

**Log (short)**
[04:28:41] [Async Class PreLoader/WARN]: @Redirect conflict. Skipping randompatches.mixins.json:InputSlotFillerMixin->@Redirect::getSlotWithUnusedStack(Lnet/minecraft/class_1661;Lnet/minecraft/class_1799;)I with priority 1000, already redirected by nbtcrafting.mixins.json:MixinInputSlotFiller->@Redirect::playerInventoryFindStack(Lnet/minecraft/class_1661;Lnet/minecraft/class_1799;)I with priority 1000
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at com.fox2code.fabriczero.FabricZeroTransformerHook.transformClassBytes(FabricZeroTransformerHook.java:41)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:163)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at java.lang.Class.forName0(Native Method)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at java.lang.Class.forName(Unknown Source)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at com.fox2code.fabriczero.mod.FabricZeroClient$1.run(FabricZeroClient.java:41)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector getSlotWithUnusedStack(Lnet/minecraft/class_1661;Lnet/minecraft/class_1799;)I in randompatches.mixins.json:InputSlotFillerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap randompatches-refmap.json
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	... 15 more

**Log (entire)**
MultiMC version: 0.6.11-1430

Minecraft folder is:
E:/minecraft/multiMC/mmc-stable-win32/MultiMC/instances/Single Mod Test/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_271, using 64-bit architecture.

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/instances/Single Mod Test/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/intermediary/1.16.4/intermediary-1.16.4.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/tiny-remapper/0.3.0.70/tiny-remapper-0.3.0.70.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/access-widener/1.0.0/access-widener-1.0.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/google/jimfs/jimfs/1.2-fabric/jimfs-1.2-fabric.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm/9.0/asm-9.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-analysis/9.0/asm-analysis-9.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-commons/9.0/asm-commons-9.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-tree/9.0/asm-tree-9.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-util/9.0/asm-util-9.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/fabric-loader/0.10.8/fabric-loader-0.10.8.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.16.4/minecraft-1.16.4-client.jar

Native libraries:
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [❌] advdebug-2.2.0.jar (disabled)
  [❌] amecs-1.3.2+mc.1.16.3.jar (disabled)
  [❌] antighost-1.16.4-fabric0.25.1-1.1.3.jar (disabled)
  [❌] autoconfig1u-3.3.1.jar (disabled)
  [❌] blame-2.2.5.jar (disabled)
  [❌] Cardinal-Components-API-2.7.10.jar (disabled)
  [❌] cloth-api-1.4.9.jar (disabled)
  [❌] config-2-4.8.3.jar (disabled)
  [❌] dark-loading-screen-1.5.0.jar (disabled)
  [❌] dawn-1.6.1.jar (disabled)
  [❌] DisableCustomWorldsAdvice-1.2.jar (disabled)
  [❌] dynamic-fps-1.2.1.jar (disabled)
  [✔️] fabric-api-0.29.0+1.16
  [❌] fabric-chunkpregen-0.3.3.jar (disabled)
  [❌] fabric-language-kotlin-1.4.21+build.1.jar (disabled)
  [✔️] fabriczero-0.2.0
  [❌] fastbench-2.3.jar (disabled)
  [❌] fastfurnace-2.3.jar (disabled)
  [❌] fatxporbs-0.0.9+1.16.4.jar (disabled)
  [❌] inventory-hotswap-1.16-1.1.1.jar (disabled)
  [❌] item-model-fix-0.2.4.jar (disabled)
  [❌] juke-fix-1.0.0.jar (disabled)
  [❌] konkrete_fabric_1.1.0_MC_1.16.3-1.16.4.jar (disabled)
  [❌] lithium-fabric-mc1.16.4-0.6.0.jar (disabled)
  [❌] modmenu-1.14.13+build.19.jar (disabled)
  [❌] mousewheelie-1.6.1+mc1.16.4.jar (disabled)
  [✔️] nbtcrafting-2.0.3+mc1.16.4
  [❌] phosphor-fabric-mc1.16.3-0.7.0+build.10.jar (disabled)
  [✔️] randompatches-2.1.0
  [❌] RoughlyEnoughItems-5.8.9.jar (disabled)
  [❌] smoothboot-fabric-1.16-1.3.1.jar (disabled)
  [❌] sodium-fabric-mc1.16.3-0.1.0.jar (disabled)
  [❌] spark-fabric.jar (disabled)
  [❌] YungsApi-1.16.4-Fabric-1.jar (disabled)

Params:
  --username  --version MultiMC5 --gameDir E:/minecraft/multiMC/mmc-stable-win32/MultiMC/instances/Single Mod Test/.minecraft --assetsDir E:/minecraft/multiMC/mmc-stable-win32/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms4096m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 16036

Using onesix launcher.

[04:28:30] [main/INFO]: Loading for game Minecraft 1.16.4
[04:28:31] [main/INFO]: [FabricLoader] Loading 53 mods: fabric-renderer-api-v1@0.4.0+cbe9176f3a, fabric-keybindings-v0@0.2.0+6a2618f53a, fabricloader@0.10.8, fabric-structure-api-v1@1.1.3+cbe9176f3a, fabriczero@0.2.0, fabric-containers-v0@0.1.9+a03e98793a, fabric-object-builder-api-v1@1.9.2+6a2618f53a, fabric-dimensions-v1@2.0.1+9a6c75813a, fabric-game-rule-api-v1@1.0.5+cbe9176f3a, fabric-api-base@0.2.0+ab87788d3a, fabric-rendering-data-attachment-v1@0.1.4+6a2618f53a, fabric-textures-v0@1.0.5+6a2618f53a, com_electronwill_night-config_core@3.6.3, randompatches@2.0.1, fabric-rendering-fluids-v1@0.1.12+6a2618f53a, fabric-blockrenderlayer-v1@1.1.4+6a2618f53a, fabric-lifecycle-events-v1@1.2.0+ffb68a873a, fabric-renderer-registries-v1@2.2.0+6a2618f53a, fabric-loot-tables-v1@1.0.1+6a2618f53a, fabric@0.29.0+1.16, fabric-particles-v1@0.2.3+cbe9176f3a, autoconfigtoml@1.0.0, fabric-networking-v0@0.3.1+2a4333d33a, minecraft@1.16.4, fabric-screen-handler-api-v1@1.1.0+6a2618f53a, fabric-networking-blockentity-v0@0.2.7+a03e98793a, cloth-basic-math@0.5.1, fabric-command-api-v1@1.0.9+6a2618f53a, fabric-tool-attribute-api-v1@1.2.5+6a2618f53a, fabric-renderer-indigo@0.4.3+6a2618f53a, com_electronwill_night-config_toml@3.6.3, fabric-item-api-v1@1.2.0+6a2618f53a, fabric-events-interaction-v0@0.4.1+6a2618f53a, fabric-crash-report-info-v1@0.1.2+b7f9825d3a, fabric-entity-events-v1@1.0.0+79b23bee3a, nbtcrafting@2.0.3+mc1.16.4, fabric-rendering-v0@1.1.1+6a2618f53a, fabric-rendering-v1@1.5.0+c26373133a, fabric-key-binding-api-v1@1.0.1+730711c63a, cloth-config2@4.8.3, autoconfig1u@3.3.1, fabric-resource-loader-v0@0.4.0+552549d53a, fabric-content-registries-v0@0.2.0+e77439c73a, fabric-tag-extensions-v0@1.1.0+e77439c73a, fabric-biome-api-v1@3.1.0+2e23b97c3a, fabric-registry-sync-v0@0.7.3+be155ae23a, fabric-commands-v0@0.2.1+cbe9176f3a, fabric-mining-levels-v0@0.1.2+6a2618f53a, fabric-networking-api-v1@1.0.0+4358fbc63a, fabric-events-lifecycle-v0@0.2.0+6a2618f53a, fabric-models-v0@0.2.0+cbe9176f3a, fabric-item-groups-v0@0.2.2+cbe9176f3a, fabric-object-builders-v0@0.7.1+6a2618f53a
[04:28:31] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[04:28:31] [main/INFO]: FabricZero: Loaded!
[04:28:31] [main/WARN]: Error loading class: me/shedaniel/rei/server/RecipeFinder (java.lang.ClassNotFoundException: me/shedaniel/rei/server/RecipeFinder)
[04:28:31] [main/WARN]: @Mixin target me/shedaniel/rei/server/RecipeFinder was not found nbtcrafting.compat.mixins.json:MixinREIRecipeFinder
[04:28:38] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[04:28:39] [main/INFO]: Setting user: Josheva
[04:28:40] [Async Class PreLoader/INFO]: Preloading classes...
[04:28:40] [main/INFO]: [STDOUT]: E:\minecraft\multiMC\mmc-stable-win32\MultiMC\libraries\com\mojang\minecraft\1.16.4\minecraft-1.16.4-client.jar
[04:28:40] [main/INFO]: [Indigo] Registering Indigo renderer!
[04:28:41] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[04:28:41] [Async Class PreLoader/WARN]: @Redirect conflict. Skipping randompatches.mixins.json:InputSlotFillerMixin->@Redirect::getSlotWithUnusedStack(Lnet/minecraft/class_1661;Lnet/minecraft/class_1799;)I with priority 1000, already redirected by nbtcrafting.mixins.json:MixinInputSlotFiller->@Redirect::playerInventoryFindStack(Lnet/minecraft/class_1661;Lnet/minecraft/class_1799;)I with priority 1000
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at com.fox2code.fabriczero.FabricZeroTransformerHook.transformClassBytes(FabricZeroTransformerHook.java:41)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:163)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at java.lang.Class.forName0(Native Method)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at java.lang.Class.forName(Unknown Source)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at com.fox2code.fabriczero.mod.FabricZeroClient$1.run(FabricZeroClient.java:41)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector getSlotWithUnusedStack(Lnet/minecraft/class_1661;Lnet/minecraft/class_1799;)I in randompatches.mixins.json:InputSlotFillerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap randompatches-refmap.json
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[04:28:41] [Async Class PreLoader/INFO]: [STDERR]: 	... 15 more
[04:28:44] [main/INFO]: Narrator library for x64 successfully loaded
[04:28:44] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Renderer API (v1), Fabric Key Bindings (v0), Fabric Loader, Fabric Structure API (v1), Fabric Zero, Fabric Containers (v0), Fabric Object Builder API (v1), Fabric Game Rule API (v1), Fabric API Base, Fabric Rendering Data Attachment (v1), Fabric Textures (v0), RandomPatches, Fabric Rendering Fluids (v1), Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric API, Fabric Particles (v1), AutoConfig-TOML, Fabric Networking (v0), Fabric Screen Handler API (v1), Fabric Networking Block Entity (v0), Fabric Command API (v1), Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Item API (v1), Fabric Events Interaction (v0), Fabric Crash Report Info (v1), Fabric Entity Events (v1), NBT Crafting, Fabric Rendering (v0), Fabric Rendering (v1), Fabric Key Binding API (v1), Cloth Config v4, Auto Config v1 Updated, Fabric Resource Loader (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Biome API (v1), Fabric Registry Sync (v0), Fabric Commands (v0), Fabric Mining Levels (v0), Fabric Networking API (v1), Fabric Events Lifecycle (v0), Fabric Models (v0), Fabric Item Groups (v0), Fabric Object Builders (v0))
[04:28:51] [main/INFO]: OpenAL initialized.
[04:28:51] [main/INFO]: Sound engine started
[04:28:52] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[04:28:52] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[04:28:52] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[04:28:52] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[04:28:52] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[04:28:52] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[04:28:52] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[04:28:53] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[04:28:53] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[04:28:53] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[04:29:20] [main/INFO]: Stopping!
Exception in thread "Async Class PreLoader" 
Process exited with code 0.

**Comment by FewerFlaws** [comment]
Please let me know if adjusting any settings for this mod will resolve the issue properly.  Thank you =]

The same issue:
https://github.com/Siphalor/nbt-crafting/issues/60
https://github.com/TheRandomLabs/RandomPatches/issues/158
https://github.com/Fox2Code/FabricZero/issues/12

**Comment by TheRandomLabs** [comment]
Add `"InputSlotFiller"` to `misc.mixin_blacklist` for now. I'll fix this very soon.
