### ISSUE TITLE
Krypton incompatibility (wait until next version of Krypton)

### ISSUE THREAD

**Issue by shouxd** [TheRandomLabs/RandomPatches#159]
Hi! I updated to last randompatches fabric and since then I cant enter my server. Mod is in both server and client, but whenever I try to join I get this in server console:

> [08:58:33] [Netty Epoll Server IO #0/FATAL]: Mixin apply failed randompatches.mixins.json:packetsizelimits.PacketInflaterMixin -> net.minecraft.class_2532: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("CONSTANT") on net/minecraft/class_2532::getMaxCompressedPacketSize with priority 1000 cannot inject into net/minecraft/class_2532::decode(Lio/netty/channel/ChannelHandlerContext;Lio/netty/buffer/ByteBuf;Ljava/util/List;)V merged by me.steinborn.krypton.mixin.network.pipeline.PacketInflaterMixin with priority 1000 [PREINJECT Applicator Phase -> randompatches.mixins.json:packetsizelimits.PacketInflaterMixin -> Prepare Injections ->  -> constant$cca000$getMaxCompressedPacketSize(I)I -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("CONSTANT") on net/minecraft/class_2532::getMaxCompressedPacketSize with priority 1000 cannot inject into net/minecraft/class_2532::decode(Lio/netty/channel/ChannelHandlerContext;Lio/netty/buffer/ByteBuf;Ljava/util/List;)V merged by me.steinborn.krypton.mixin.network.pipeline.PacketInflaterMixin with priority 1000 [PREINJECT Applicator Phase -> randompatches.mixins.json:packetsizelimits.PacketInflaterMixin -> Prepare Injections ->  -> constant$cca000$getMaxCompressedPacketSize(I)I -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_2535.method_10760(class_2535.java:365) ~[intermediary-server.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerLoginNetworkAddon.lambda$sendCompressionPacket$2(ServerLoginNetworkAddon.java:118) ~[775425c0-3945-43b7-8ed1-130ebd1f66b3.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) ~[intermediary-server.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504) ~[intermediary-server.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483) ~[intermediary-server.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) ~[intermediary-server.jar:?]
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103) ~[intermediary-server.jar:?]
	at io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48) ~[intermediary-server.jar:?]
	at io.netty.channel.ChannelOutboundBuffer.safeSuccess(ChannelOutboundBuffer.java:696) ~[intermediary-server.jar:?]
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:258) ~[intermediary-server.jar:?]
	at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:338) ~[intermediary-server.jar:?]
	at io.netty.channel.epoll.AbstractEpollChannel.doWriteBytes(AbstractEpollChannel.java:363) ~[intermediary-server.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel.writeBytes(AbstractEpollStreamChannel.java:274) ~[intermediary-server.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel.doWriteSingle(AbstractEpollStreamChannel.java:483) ~[intermediary-server.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel.doWrite(AbstractEpollStreamChannel.java:441) ~[intermediary-server.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934) ~[intermediary-server.jar:?]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:516) ~[intermediary-server.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:901) ~[intermediary-server.jar:?]
	at io.netty.channel.DefaultChannel[08:58:33] [Server thread/INFO]: com.mojang.authlib.GameProfile@17aed8f0[id=<null>,name=Sofianne,properties={},legacy=false] (/186.116.27.125:52293) lost connection: Disconnected
	
This results in a message saying "Failed to connect to server". Last RandomPatches version I was using was 0.0.0.5.

**Comment by TheRandomLabs** [comment]
Thanks for reporting. This is an incompatibility with Krypton, which I'll fix very soon.

**Comment by TheRandomLabs** [comment]
Add `"PacketInflater"` to `misc.mixin_blacklist`. It's looking like this issue will be fixed with the next version of Krypton. 😄

**Comment by astei** [comment]
FYI, Krypton still enforces a 2MiB limit on uncompressed packets, but there is a system property to raise it to 16MiB. I'll add in a config option to allow it to be user configurable in the next release.

**Comment by User198263321** [comment]
Same issue for me.

**Comment by astei** [comment]
@Michael19723 The latest [Krypton build](https://ci.velocitypowered.com/job/krypton/) should work.

**Comment by TheRandomLabs** [comment]
Thank you! 😄
