### ISSUE TITLE
Reliable crash on startup

### ISSUE THREAD

**Issue by FewerFlaws** [TheRandomLabs/RandomPatches#161]
Just updated to 2.1.1 for fabric and it's crashing on startup every time with Fabric API as the only other mod installed.  This will happen whether NBT crafting is installed or not.

Log: Short
```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 31/12/20 7:29 PM
Description: Initializing game

java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;
	at com.therandomlabs.randompatches.client.RPWindowHandler.readImageToBuffer(RPWindowHandler.java:352)
	at com.therandomlabs.randompatches.client.RPWindowHandler.updateWindowIcon(RPWindowHandler.java:249)
	at com.therandomlabs.randompatches.client.RPWindowHandler.updateWindowIcon(RPWindowHandler.java:184)
	at net.minecraft.class_310.redirect$zhk000$setIcon(class_310.java:4899)
	at net.minecraft.class_310.<init>(class_310.java:466)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.therandomlabs.randompatches.client.RPWindowHandler.readImageToBuffer(RPWindowHandler.java:352)
	at com.therandomlabs.randompatches.client.RPWindowHandler.updateWindowIcon(RPWindowHandler.java:249)
	at com.therandomlabs.randompatches.client.RPWindowHandler.updateWindowIcon(RPWindowHandler.java:184)
	at net.minecraft.class_310.redirect$zhk000$setIcon(class_310.java:4899)
	at net.minecraft.class_310.<init>(class_310.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```
Log: Complete
```
MultiMC version: 0.6.11-1430


Minecraft folder is:
E:/minecraft/multiMC/mmc-stable-win32/MultiMC/instances/Single Mod Test/.minecraft


Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe


Java is version 1.8.0_271, using 64-bit architecture.


Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/instances/Single Mod Test/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/intermediary/1.16.4/intermediary-1.16.4.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/tiny-remapper/0.3.0.70/tiny-remapper-0.3.0.70.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/access-widener/1.0.0/access-widener-1.0.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/google/jimfs/jimfs/1.2-fabric/jimfs-1.2-fabric.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm/9.0/asm-9.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-analysis/9.0/asm-analysis-9.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-commons/9.0/asm-commons-9.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-tree/9.0/asm-tree-9.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-util/9.0/asm-util-9.0.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/fabric-loader/0.10.8/fabric-loader-0.10.8.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.16.4/minecraft-1.16.4-client.jar

Native libraries:
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [❌] advdebug-2.2.0.jar (disabled)
  [❌] amecs-1.3.2+mc.1.16.3.jar (disabled)
  [❌] antighost-1.16.4-fabric0.25.1-1.1.3.jar (disabled)
  [❌] autoconfig1u-3.3.1.jar (disabled)
  [❌] blame-2.2.6.jar (disabled)
  [❌] Cardinal-Components-API-2.7.10.jar (disabled)
  [❌] cloth-api-1.4.9.jar (disabled)
  [❌] config-2-4.8.3.jar (disabled)
  [❌] dark-loading-screen-1.5.0.jar (disabled)
  [❌] dawn-1.6.1.jar (disabled)
  [❌] DisableCustomWorldsAdvice-1.2.jar (disabled)
  [❌] dynamic-fps-1.2.1.jar (disabled)
  [✔️] fabric-api-0.29.0+1.16
  [❌] fabric-chunkpregen-0.3.3.jar (disabled)
  [❌] fabric-language-kotlin-1.4.21+build.1.jar (disabled)
  [❌] fabriczero-0.2.0.jar (disabled)
  [❌] fastbench-2.3.jar (disabled)
  [❌] fastfurnace-2.3.jar (disabled)
  [❌] fatxporbs-0.0.9+1.16.4.jar (disabled)
  [❌] inventory-hotswap-1.16-1.1.1.jar (disabled)
  [❌] item-model-fix-0.2.4.jar (disabled)
  [❌] juke-fix-1.0.0.jar (disabled)
  [❌] konkrete_fabric_1.1.0_MC_1.16.3-1.16.4.jar (disabled)
  [❌] lithium-fabric-mc1.16.4-0.6.0.jar (disabled)
  [❌] modmenu-1.14.13+build.19.jar (disabled)
  [❌] mousewheelie-1.6.1+mc1.16.4.jar (disabled)
  [❌] nbtcrafting-2.0.3+mc1.16.4.jar (disabled)
  [❌] phosphor-fabric-mc1.16.3-0.7.0+build.10.jar (disabled)
  [✔️] randompatches-2.1.1-fabric
  [❌] RoughlyEnoughItems-5.8.9.jar (disabled)
  [❌] smoothboot-fabric-1.16.4-1.3.2.jar (disabled)
  [❌] sodium-fabric-mc1.16.3-0.1.0.jar (disabled)
  [❌] spark-fabric.jar (disabled)
  [❌] YungsApi-1.16.4-Fabric-1.jar (disabled)

Params:
  --username  --version MultiMC5 --gameDir E:/minecraft/multiMC/mmc-stable-win32/MultiMC/instances/Single Mod Test/.minecraft --assetsDir E:/minecraft/multiMC/mmc-stable-win32/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms4096m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 13964


Using onesix launcher.

[19:29:40] [main/INFO]: Loading for game Minecraft 1.16.4
[19:29:41] [main/INFO]: [FabricLoader] Loading 51 mods: fabric-renderer-api-v1@0.4.0+cbe9176f3a, fabric-keybindings-v0@0.2.0+6a2618f53a, fabricloader@0.10.8, fabric-structure-api-v1@1.1.3+cbe9176f3a, fabric-containers-v0@0.1.9+a03e98793a, fabric-object-builder-api-v1@1.9.2+6a2618f53a, fabric-dimensions-v1@2.0.1+9a6c75813a, fabric-game-rule-api-v1@1.0.5+cbe9176f3a, fabric-api-base@0.2.0+ab87788d3a, fabric-rendering-data-attachment-v1@0.1.4+6a2618f53a, fabric-textures-v0@1.0.5+6a2618f53a, com_electronwill_night-config_core@3.6.3, randompatches@2.1.1-fabric, fabric-rendering-fluids-v1@0.1.12+6a2618f53a, fabric-blockrenderlayer-v1@1.1.4+6a2618f53a, fabric-lifecycle-events-v1@1.2.0+ffb68a873a, fabric-renderer-registries-v1@2.2.0+6a2618f53a, fabric-loot-tables-v1@1.0.1+6a2618f53a, fabric@0.29.0+1.16, fabric-particles-v1@0.2.3+cbe9176f3a, autoconfigtoml@1.0.0, fabric-networking-v0@0.3.1+2a4333d33a, minecraft@1.16.4, fabric-screen-handler-api-v1@1.1.0+6a2618f53a, fabric-networking-blockentity-v0@0.2.7+a03e98793a, cloth-basic-math@0.5.1, fabric-command-api-v1@1.0.9+6a2618f53a, fabric-tool-attribute-api-v1@1.2.5+6a2618f53a, fabric-renderer-indigo@0.4.3+6a2618f53a, com_electronwill_night-config_toml@3.6.3, fabric-item-api-v1@1.2.0+6a2618f53a, fabric-events-interaction-v0@0.4.1+6a2618f53a, fabric-crash-report-info-v1@0.1.2+b7f9825d3a, fabric-entity-events-v1@1.0.0+79b23bee3a, fabric-rendering-v0@1.1.1+6a2618f53a, fabric-rendering-v1@1.5.0+c26373133a, fabric-key-binding-api-v1@1.0.1+730711c63a, cloth-config2@4.8.3, fabric-resource-loader-v0@0.4.0+552549d53a, autoconfig1u@3.3.1, fabric-content-registries-v0@0.2.0+e77439c73a, fabric-tag-extensions-v0@1.1.0+e77439c73a, fabric-biome-api-v1@3.1.0+2e23b97c3a, fabric-registry-sync-v0@0.7.3+be155ae23a, fabric-commands-v0@0.2.1+cbe9176f3a, fabric-mining-levels-v0@0.1.2+6a2618f53a, fabric-networking-api-v1@1.0.0+4358fbc63a, fabric-events-lifecycle-v0@0.2.0+6a2618f53a, fabric-models-v0@0.2.0+cbe9176f3a, fabric-item-groups-v0@0.2.2+cbe9176f3a, fabric-object-builders-v0@0.7.1+6a2618f53a
[19:29:41] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/E:/minecraft/multiMC/mmc-stable-win32/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[19:29:46] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:29:48] [main/INFO]: Setting user: Josheva
[19:29:48] [main/INFO]: [Indigo] Registering Indigo renderer!
[19:29:49] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 31/12/20 7:29 PM
Description: Initializing game

java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;
	at com.therandomlabs.randompatches.client.RPWindowHandler.readImageToBuffer(RPWindowHandler.java:352)
	at com.therandomlabs.randompatches.client.RPWindowHandler.updateWindowIcon(RPWindowHandler.java:249)
	at com.therandomlabs.randompatches.client.RPWindowHandler.updateWindowIcon(RPWindowHandler.java:184)
	at net.minecraft.class_310.redirect$zhk000$setIcon(class_310.java:4899)
	at net.minecraft.class_310.<init>(class_310.java:466)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.therandomlabs.randompatches.client.RPWindowHandler.readImageToBuffer(RPWindowHandler.java:352)
	at com.therandomlabs.randompatches.client.RPWindowHandler.updateWindowIcon(RPWindowHandler.java:249)
	at com.therandomlabs.randompatches.client.RPWindowHandler.updateWindowIcon(RPWindowHandler.java:184)
	at net.minecraft.class_310.redirect$zhk000$setIcon(class_310.java:4899)
	at net.minecraft.class_310.<init>(class_310.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3882633200 bytes (3702 MB) / 4140826624 bytes (3949 MB) up to 4140826624 bytes (3949 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx4096m
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autoconfigtoml: AutoConfig-TOML 1.0.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.3
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		fabric: Fabric API 0.29.0+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.1+cbe9176f3a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.0+79b23bee3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.5+cbe9176f3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.2+cbe9176f3a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-models-v0: Fabric Models (v0) 0.2.0+cbe9176f3a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: Fabric Particles (v1) 0.2.3+cbe9176f3a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.0+cbe9176f3a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.0+c26373133a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.0+552549d53a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.3+cbe9176f3a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		minecraft: Minecraft 1.16.4
		randompatches: RandomPatches 2.1.1-fabric
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 457.30, NVIDIA Corporation
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# E:\minecraft\multiMC\mmc-stable-win32\MultiMC\instances\Single Mod Test\.minecraft\crash-reports\crash-2020-12-31_19.29.51-client.txt
Process exited with code -1.
```

**Comment by TheRandomLabs** [comment]
I don't know how, but I think Gradle managed to use JDK 14 to compile again. 😞 
**EDIT:** Ah, figured out why. I'll have to make sure this doesn't happen again...
**EDIT 2:** This will *not* happen again; I've fixed it in my buildscript.

**Comment by FewerFlaws** [comment]
Hahhaa, first good laugh of the year.  Cheers, dude.  2.1.2 works.  Thank you =D
