### ISSUE TITLE
Incompatible with Fabritone/Baritone

### ISSUE THREAD

**Issue by linuzzx** [TheRandomLabs/RandomPatches#185]
It doesn't start when [Fabritone](https://gitlab.com/CDAGaming/fabritone) is installed.

Note Baritone is a Minecraft AI based bot that can auto build/break, walk etc. I don't see this as a creative project rather than something like a hacked client!
Example:
[https://www.youtube.com/watch?v=4m4hFel4q1c](https://www.youtube.com/watch?v=4m4hFel4q1c )

Error:
`[16:46:36] [main/INFO]: Loading for game Minecraft 1.16.4
[16:46:37] [main/INFO]: [FabricLoader] Loading 12 mods: minecraft@1.16.4, autoconfig1u@3.3.1, com_electronwill_night-config_toml@3.6.3, java@8, baritoe@1.6.1, com_electronwill_night-config_core@3.6.3, cloth-basic-math@0.5.1, fabricloader@0.11.1, randompatches@2.1.8-fabric, autoconfigtoml@1.0.0-fabric, fabric-api-base@0.1.3+12a8474c34, cloth-config2@4.8.3
[16:46:37] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Program%20Files%20(x86)/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[16:46:49] [main/WARN]: @Redirect conflict. Skipping randompatches.mixins.json:client.keybindings.ClientPlayerEntityMixin->@Redirect::isSprintKeyDown(Lnet/minecraft/class_304;)Z with priority 1000, already redirected by mixins.baritone.json:MixinClientPlayerEntity->@Redirect::isKeyDown(Lnet/minecraft/class_304;)Z with priority 1000
[16:46:49] [main/WARN]: @Redirect conflict. Skipping randompatches.mixins.json:client.keybindings.ClientPlayerEntityMixin->@Redirect::isSprintKeyDown(Lnet/minecraft/class_304;)Z with priority 1000, already redirected by mixins.baritone.json:MixinClientPlayerEntity->@Redirect::isKeyDown(Lnet/minecraft/class_304;)Z with priority 1000
[16:46:49] [main/WARN]: @Redirect conflict. Skipping randompatches.mixins.json:client.keybindings.ClientPlayerEntityMixin->@Redirect::isSprintKeyDown(Lnet/minecraft/class_304;)Z with priority 1000, already redirected by mixins.baritone.json:MixinClientPlayerEntity->@Redirect::isKeyDown(Lnet/minecraft/class_304;)Z with priority 1000
[16:46:49] [main/WARN]: @Redirect conflict. Skipping randompatches.mixins.json:client.keybindings.ClientPlayerEntityMixin->@Redirect::isSprintKeyDown(Lnet/minecraft/class_304;)Z with priority 1000, already redirected by mixins.baritone.json:MixinClientPlayerEntity->@Redirect::isKeyDown(Lnet/minecraft/class_304;)Z with priority 1000
[16:46:49] [main/INFO]: [STDERR]: Failed to start Minecraft:
[16:46:49] [main/INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
[16:46:49] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:46:49] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:46:49] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:46:49] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:46:49] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[16:46:49] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[16:46:49] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[16:46:49] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[16:46:49] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[16:46:49] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
[16:46:49] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
[16:46:49] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
[16:46:49] [main/INFO]: [STDERR]: 	... 8 more
[16:46:49] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[16:46:49] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:46:49] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:46:49] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:46:49] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:46:49] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
[16:46:49] [main/INFO]: [STDERR]: 	... 10 more
[16:46:49] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[16:46:50] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[16:46:50] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
[16:46:50] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[16:46:50] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[16:46:50] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
[16:46:50] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
[16:46:50] [main/INFO]: [STDERR]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[16:46:50] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:185)
[16:46:50] [main/INFO]: [STDERR]: 	... 15 more
[16:46:50] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector isSprintKeyDown(Lnet/minecraft/class_304;)Z in randompatches.mixins.json:client.keybindings.ClientPlayerEntityMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap randompatches-refmap.json
[16:46:50] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
[16:46:50] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
[16:46:50] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[16:46:50] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[16:46:50] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[16:46:50] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[16:46:50] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[16:46:50] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[16:46:50] [main/INFO]: [STDERR]: 	... 22 more
[16:46:50] [main/INFO]: [STDOUT]: Exiting with -1
2021-01-29 16:46:50,348 Client Shutdown Thread WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger`

**Comment by linuzzx** [comment]
bdw I don't know how to add labels like "bug"

**Comment by TheRandomLabs** [comment]
Nah, only I can add labels. 😉
