### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Romz24** [TheRandomLabs/RandomPatches#22]
```
[20:21:25] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at mods.railcraft.common.blocks.machine.worldspike.TileWorldspike.func_73660_a(TileWorldspike.java:268) ~[TileWorldspike.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1835) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more
```

Crash log: https://pastebin.com/7eadnZjA

**Comment by TheRandomLabs** [comment]
As far as I can tell, this crash has nothing to do with RandomPatches. However, it does look very similar to Railcraft/Railcraft#1594.
