### ISSUE TITLE
IllegalArgumentException: Multiple entries with same key

### ISSUE THREAD

**Issue by Sir-Will** [TheRandomLabs/RandomPatches#26]
randompatches-1.12.2-1.14.0.0
```
Time: 3/2/19 7:51 AM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Multiple entries with same key: randompatches=Wrapped{randompatches} and randompatches=Wrapped{randompatches}. To index multiple values under a key, use Multimaps.index.
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1385)
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1341)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:427)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:566)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1385)
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1341)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:427)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:566)

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjn000(MinecraftServer.java:3965)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:371)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by TheRandomLabs** [comment]
Can you make sure you do not have multiple versions of RandomPatches installed and that you've downloaded the [right one](https://minecraft.curseforge.com/projects/randompatches/files/2677373/download)?

**Comment by Sir-Will** [comment]
Woops, my bad. Looks like I missed that there is a different version already installed. Sorry!
