### ISSUE TITLE
mixinBlacklist `Failed to deserialize: class com.therandomlabs.randompatches.RPConfig`

### ISSUE THREAD

**Issue by SettingDust** [TheRandomLabs/RandomPatches#274]
```java
[23:24:19] [main/ERROR]: Failed to deserialize: class com.therandomlabs.randompatches.RPConfig
com.electronwill.nightconfig.core.io.ParsingException: Invalid value: ServerPlayNetHandlerKeepAlive
	at com.electronwill.nightconfig.toml.ValueParser.parseNumber(ValueParser.java:101) ~[toml-3.6.3.jar:?]
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:63) ~[toml-3.6.3.jar:?]
	at com.electronwill.nightconfig.toml.ArrayParser.parse(ArrayParser.java:31) ~[toml-3.6.3.jar:?]
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:32) ~[toml-3.6.3.jar:?]
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:68) ~[toml-3.6.3.jar:?]
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:57) ~[toml-3.6.3.jar:?]
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:101) ~[toml-3.6.3.jar:?]
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:88) ~[toml-3.6.3.jar:?]
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.3.jar:?]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.3.jar:?]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.3.jar:?]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.3.jar:?]
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.3.jar:?]
	at com.electronwill.nightconfig.core.file.SimpleCommentedFileConfig.load(SimpleCommentedFileConfig.java:38) ~[core-3.6.3.jar:?]
	at com.therandomlabs.randompatches.shadowed.com.therandomlabs.autoconfigtoml.TOMLConfigSerializer.deserialize(TOMLConfigSerializer.java:241) ~[randompatches:2.4.4-forge]
	at com.therandomlabs.randompatches.shadowed.me.shedaniel.autoconfig1u.ConfigManager.load(ConfigManager.java:52) ~[randompatches:2.4.4-forge]
	at com.therandomlabs.randompatches.shadowed.me.shedaniel.autoconfig1u.ConfigManager.<init>(ConfigManager.java:25) ~[randompatches:2.4.4-forge]
	at com.therandomlabs.randompatches.shadowed.me.shedaniel.autoconfig1u.AutoConfig.register(AutoConfig.java:45) ~[randompatches:2.4.4-forge]
	at com.therandomlabs.randompatches.RandomPatches.reloadConfig(RandomPatches.java:104) ~[randompatches:2.4.4-forge]
	at com.therandomlabs.randompatches.RandomPatches.config(RandomPatches.java:93) ~[randompatches:2.4.4-forge]
	at com.therandomlabs.randompatches.mixin.RPMixinConfig.shouldApplyMixin(RPMixinConfig.java:61) ~[randompatches:2.4.4-forge]
```

**Comment by SettingDust** [comment]
Caused by the toml string have to surround with quotes
