### ISSUE TITLE
Mod is preventing my son from joining a LAN game?

### ISSUE THREAD

**Issue by FatalScroll** [TheRandomLabs/RandomPatches#35]
[16:48:57] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$PlayerTickEvent@41793a11:
java.lang.NullPointerException: null
    at net.minecraft.world.Teleporter.func_180620_b(Teleporter.java:134) ~[anc.class:?]
    at com.therandomlabs.randompatches.common.RPTeleporter.func_180620_b(RPTeleporter.java:46) ~[randompatches-1.12.2-1.15.0.2.jar:?]
    at net.minecraft.world.Teleporter.func_180266_a(Teleporter.java:34) ~[anc.class:?]
    at com.therandomlabs.randompatches.common.RPTeleporter.func_180266_a(RPTeleporter.java:37) ~[randompatches-1.12.2-1.15.0.2.jar:?]
    at net.minecraft.world.Teleporter.placeEntity(Teleporter.java:436) ~[anc.class:?]
    at com.therandomlabs.randompatches.common.RPTeleporter.placeEntity(RPTeleporter.java:73) ~[randompatches-1.12.2-1.15.0.2.jar:?]
    at net.minecraft.server.management.PlayerList.transferEntityToWorld(PlayerList.java:721) ~[pl.class:?]
    at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:624) ~[pl.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.changeDimension(EntityPlayerMP.java:695) ~[oq.class:?]
    at net.minecraft.entity.Entity.func_184204_a(Entity.java:2543) ~[vg.class:?]
    at the_fireplace.unforgivingvoid.UnforgivingVoid.onPlayerTick(UnforgivingVoid.java:114) ~[UnforgivingVoid.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1103_UnforgivingVoid_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:365) [FMLCommonHandler.class:?]
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:190) [aed.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) [oq.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) [pa.class:?]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]

**Comment by TheRandomLabs** [comment]
I don't think RandomPatches has anything to do with this, but could you try without it to confirm?

**Comment by FatalScroll** [comment]
It seems so, I got my son into the game without it enabled

**Comment by TheRandomLabs** [comment]
I have not been able to reproduce this issue.

**Comment by TheRandomLabs** [comment]
I forgot to ask this earlier, but can you try setting `misc.replaceTeleporter` to `false` in `config/randompatches.cfg`?

**Comment by TheRandomLabs** [comment]
I've removed the Teleporter replacement patch and am assuming this is fixed.
