### ISSUE TITLE
Server crash in NetHandlerPlayServer

### ISSUE THREAD

**Issue by LemADEC** [TheRandomLabs/RandomPatches#5]
As of 1.12.2-1.2.1.0, server crashes in NetHandlerPlayServer.
```
[18:01:56] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchFieldError: g
>       at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:231) ~[pa.class:?]
>       at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
>       at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
>       at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) ~[oz.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) ~[MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by TheRandomLabs** [comment]
1.12.2-1.2.1.1 should fix this. :)
