### ISSUE TITLE
28.0.45

### ISSUE THREAD

**Issue by Sunekaer** [TheRandomLabs/RandomPatches#50]
Hi 
forge 28.0.45

https://s1.sunekaer.com/files/crash-2019-08-06_19.35.02-client.txt

	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreClientTick(BasicEventHooks.java:104) ~[?:?] {}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1270) ~[?:?] {pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:865) [?:?] {pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}

**Comment by Sunekaer** [comment]
at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:857) [?:?] {pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
also
https://s1.sunekaer.com/files/crash-2019-08-06_19.04.18-client.txt

**Comment by TheRandomLabs** [comment]
I don't think RandomPatches has anything to do with this.
