### ISSUE TITLE
Minecraft 1.14.4  latest Forge version 28.1.6 causes crash when killing certain mobs

### ISSUE THREAD

**Issue by raziel23x** [TheRandomLabs/RandomPatches#59]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 9/16/19 9:47 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.Entity.func_184191_r(Entity.java:1913) ~[?:?] {pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Entity Transformer}
	at net.minecraft.entity.ai.goal.HurtByTargetGoal.func_190105_f(SourceFile:83) ~[?:?] {}
	at net.minecraft.entity.ai.goal.HurtByTargetGoal.func_75249_e(SourceFile:63) ~[?:?] {}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75249_e(SourceFile:41) ~[?:?] {}
	at net.minecraft.entity.ai.goal.GoalSelector.func_220877_a(SourceFile:75) ~[?:?] {pl:accesstransformer:B}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_212] {}
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_212] {}
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_212] {}
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_212] {}
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_212] {}
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_212] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_212] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_212] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_212] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_212] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_212] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_212] {}
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_212] {}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:69) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:587) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2186) ~[?:?] {pl:accesstransformer:B,xf:fml:apotheosis:coremodmethod,xf:fml:caelus:coremodone}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:460) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:39) ~[?:?] {}
	at net.minecraft.entity.monster.ZombieEntity.func_70636_d(ZombieEntity.java:231) ~[?:?] {}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2032) ~[?:?] {pl:accesstransformer:B,xf:fml:apotheosis:coremodmethod,xf:fml:caelus:coremodone}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.monster.MonsterEntity.func_70071_h_(SourceFile:51) ~[?:?] {}
	at net.minecraft.entity.monster.ZombieEntity.func_70071_h_(ZombieEntity.java:205) ~[?:?] {}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.world.World.func_217390_a(World.java:684) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_212] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.Entity.func_184191_r(Entity.java:1913)
	at net.minecraft.entity.ai.goal.HurtByTargetGoal.func_190105_f(SourceFile:83)
	at net.minecraft.entity.ai.goal.HurtByTargetGoal.func_75249_e(SourceFile:63)
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75249_e(SourceFile:41)
	at net.minecraft.entity.ai.goal.GoalSelector.func_220877_a(SourceFile:75)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Unknown Source)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:69)
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:587)
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2186)
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:460)
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:39)
	at net.minecraft.entity.monster.ZombieEntity.func_70636_d(ZombieEntity.java:231)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2032)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
	at net.minecraft.entity.monster.MonsterEntity.func_70071_h_(SourceFile:51)
	at net.minecraft.entity.monster.ZombieEntity.func_70071_h_(ZombieEntity.java:205)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587)

-- Entity being ticked --
Details:
	Entity Type: minecraft:zombie (net.minecraft.entity.monster.ZombieEntity)
	Entity ID: 2380
	Entity Name: Zombie
	Entity's Exact location: 145.57, 39.00, 110.27
	Entity's Block location: World: (145,39,110), Chunk: (at 1,2,14 in 9,6; contains blocks 144,0,96 to 159,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0.21, 0.36, -0.34
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:684)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['raziel23x'/557, l='Raziel23x World', x=146.56, y=39.00, z=111.86]]
	Chunk stats: ServerChunkCache: 2451
	Level dimension: DimensionType{minecraft:overworld}
	Level name: Raziel23x World
	Level seed: -8430412691993110481
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (48,76,32), Chunk: (at 0,4,0 in 3,2; contains blocks 48,0,32 to 63,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 106200 game time, 106200 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 11951 (now: false), thunder time: 45989 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_212, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3675942376 bytes (3505 MB) / 5142216704 bytes (4904 MB) up to 11453595648 bytes (10923 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.6.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.6.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.6.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.6.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.6.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.6
	FML Language Providers: 
		javafml@28.1
		minecraft@1
		kotori_scala@2.12.9
	Mod List: 
		[1.14.2-1.14.4]TorchBowMod_v1.5.jar TorchBowMod {torchbowmod@1.5 DONE}
		A Block of Charcoal-1.2.jar A Block of Charcoal {charcoalblock@1.2 DONE}
		A Block of Flint-1.0.jar A Block of Flint {flintblock@1.0 DONE}
		angelring-1.14.4-1.0.1.jar Angel Ring {angelring@1.0.1 DONE}
		Apotheosis-1.14.4-2.3.2.jar Apotheosis {apotheosis@2.3.2 DONE}
		AppleSkin-mc1.14.4-forge-1.0.12.jar AppleSkin {appleskin@1.0.12 DONE}
		AttributeFix-1.14.4-3.0.2.jar AttributeFix {attributefix@3.0.2 DONE}
		bambooeverything-1.14-1.4.0.jar Bamboo Everything {bambooeverything@1.14-1.4.0 DONE}
		bambooladders-1.14-1.0.0.jar Bamboo Ladders {bambooladders@1.14-1.0.0 DONE}
		BiomesOPlenty-1.14.4-9.0.0.253-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.253 DONE}
		buildinggadgets-3.0.5.jar Building Gadgets {buildinggadgets@3.0.5 DONE}
		caelus-FORGE-1.14.4-1.0.jar Caelus API {caelus@FORGE-1.14.4-1.0 DONE}
		campfiretorches-1.14.4-1.0.2.jar Campfire Torches {campfiretorches@1.14.4-1.0.0 DONE}
		CarryOn MC1.14.4 v1.12.3.jar Carry On {carryon@1.12.3 DONE}
		ceilingtorch-1.14.4-v1.2.2.jar Ceiling Torch {ceilingtorch@v1.2.2 DONE}
		Clumps-4.0.0.jar Clumps {clumps@4.0.0 DONE}
		colytra-FORGE-1.14.4-2.0.jar Colytra {colytra@FORGE-1.14.4-2.0 DONE}
		compact-2.6a.jar Compressed {compressed@2.6a DONE}
		ComPatchedStorage-1.14.4-2.1.1.jar ComPatchedStorage {compatchedstorage@2.1.1 DONE}
		container-1.14.4-1.0.0.jar Container {container@1.14.4-1.0.0 DONE}
		Controlling-5.0.4.jar Controlling {controlling@5.0.4 DONE}
		corail_woodcutter-1.0.6-1.14.4.jar Corail Woodcutter {corail_woodcutter@1.0.6 DONE}
		CosmeticArmorReworked-1.14.4-v1a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.14.4-v1a DONE}
		craftingstation-2.0.2a.jar Crafting Station {craftingstation@2.0.2a DONE}
		CraftingTweaks_1.14.4-10.1.3.jar Crafting Tweaks {craftingtweaks@10.1.3 DONE}
		Cucumber-1.14.4-2.0.3.jar Cucumber Library {cucumber@2.0.3 DONE}
		cursedearth-1.3a.jar Cursed Earth {cursedearth@1.3a DONE}
		Cyclic-1.14.4-0.0.11.jar Cyclic {cyclic@1.14.4-0.0.11 DONE}
		CyclopsCore-1.14.4-1.5.1.jar Cyclops Core {cyclopscore@1.5.1 DONE}
		dankstorage-1.4.jar Dank Storage {dankstorage@1.4 DONE}
		DefaultOptions_1.14.4-10.2.6.jar Default Options {defaultoptions@10.2.6 DONE}
		DefaultSettings-1.14.x-1.3.5.jar DefaultSettings {defaultsettings@1.3.5 DONE}
		Dirt2Path-1.0.0.jar Dirt2Path {d2p@1.0.0 DONE}
		EasySteel-1.14.4-1.0.33.jar Easy Steel & More {easy_steel@1.0.33 DONE}
		elevatorid-1.14.4-1.5.1.jar Elevator Mod {elevatorid@1.14.4-1.5.1 DONE}
		EnchantmentDescriptions-1.14.4-1.3.6.jar EnchantmentDescriptions {enchdesc@1.3.6 DONE}
		enchxchg-1.14.4-5.0.0.jar Enchantments Exchanger {enchxchg@1.14.4-5.0.0 DONE}
		enviromats-2.0.0.9.jar Environmental Materials {enviromats@2.0.0.9 DONE}
		essentials-1.14.4-2.5.1.jar Essentials {essentials@1.14.4-2.5.1 DONE}
		EverlastingAbilities-1.14.4-1.5.2.jar EverlastingAbilities {everlastingabilities@1.5.2 DONE}
		extcaves-1.2.jar Extended Caves {extcaves@1.2 DONE}
		f2l-0.1.8_forge.jar Flesh 2 Leather {f2l@0.1.8_forge DONE}
		FastFurnace-1.14.4-2.2.1.jar FastFurnace {fastfurnace@2.2.1 DONE}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 DONE}
		FastWorkbench-1.14.4-2.1.1.jar FastWorkbench {fastbench@2.1.1 DONE}
		firstaid-1.7.8.jar First Aid {firstaid@1.7.8 DONE}
		forbidden_arcanus-1.14.4-1.0.jar Forbidden & Arcanus {forbidden_arcanus@1.14.4-1.0-Beta-4 DONE}
		forgemod_VoxelMap-1.9.13b_for_1.14.4.jar VoxelMap {voxelmap@1.9.13 DONE}
		FTBUtilitiesBackups-2.0.0.11.jar FTB Utilities: Backups {ftbbackups@2.0.0.11 DONE}
		GemsPlusPlus-Forge-1.14.4-V1.3.2.jar GemsPlusPlus {gemsplusplus@V1.3.2 DONE}
		globaldatapack-1.14.4-1.2.1.jar Dark Roleplay - Global Datapacks {globaldatapack@1.14.4-1.2 DONE}
		Gobber2-1.14.4-2.1.93.jar Gobber 2 {gobber2@2.1.93 DONE}
		Harvest-forge-1.14.4-1.2.10-23.jar Harvest {harvest@version DONE}
		Hwyla-forge-1.10.6-B67_1.14.4.jar Waila {waila@version DONE}
		inventorysorter-1.14.4-16.0.0.jar Simple Inventory Sorter {inventorysorter@16.0.0 DONE}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
		IronJetpacks-1.14.4-2.0.2.jar Iron Jetpacks {ironjetpacks@2.0.2 DONE}
		ironshulkerboxes-1.14.4-3.1.12.jar Iron Shulker Boxes {ironshulkerbox@1.14.4-3.1.12 DONE}
		jei-1.14.4-6.0.0.11.jar Just Enough Items {jei@6.0.0.11 DONE}
		KleeSlabs_1.14.4-7.4.7.jar KleeSlabs {kleeslabs@7.4.7 DONE}
		LargeFluidTank-14.7.5.jar FluidTank {fluidtank@14.7.5 DONE}
		LLOverlayReloaded-1.2.4-mc1.14.4.jar Light Level Overlay Reloaded {llor@1.2.4-mc1.14.4 DONE}
		lycanitesmobs-1.14.4-2.1.0.0.jar Lycanites Mobs {lycanitesmobs@1.0 DONE}
		mcjtylib-1.14-3.5.6-alpha.jar McJtyLib {mcjtylib@NONE DONE}
		metalbarrels-1.3c.jar Metal Barrels {metalbarrels@1.3c DONE}
		minicoal2-1.14.4-b2-universal.jar MiniCoal 2 {minicoal2@1.14.4-b2-universal DONE}
		modnametooltip_1.14.3-1.12.1.jar Mod Name Tooltip {modnametooltip@1.12.1 DONE}
		moreprog-1.14.4-0.4.2.jar MoreProgression {moreprogression@0.4.2 DONE}
		OresAllEasy-1.14.4-1.0.1b.jar OresAllEasy {oresalleasy@1.0.1b DONE}
		Overloaded-1.14.4-0.0.75.jar Overloaded {overloaded@1.14.4-0.0.75 DONE}
		ParticleFixes-v1.1-1.14.4.jar Particle Fixes {particlefixes@1.1 DONE}
		peanutmod-1.0.2.jar Peanut Mod {peanutmod@1.0.2 DONE}
		PickleTweaks-1.14.4-3.0.6.jar Pickle Tweaks {pickletweaks@3.0.6 DONE}
		Placebo-1.14.4-2.2.1.jar Placebo {placebo@2.2.1 DONE}
		portality-1.14.4-2.0.0-5f9c6a1.jar Portality {portality@NONE DONE}
		PowderPower-1.14.4-3.0.29.jar Powder Power {powder_power@3.0.29 DONE}
		quickhomes-1.14.4-1.2.4.2.jar QuickHomes {quickhomes@1.2.4.2 DONE}
		quickteleports-1.14.4-1.1.0.jar QuickTeleports {quickteleports@1.1.0 DONE}
		randompatches-1.14.4-1.18.2.0.jar RandomPatches {randompatches@1.14.4-1.18.2.0 DONE}
		RandomThings-MC1.14.4-5.0.1.jar Random Things {randomthings@5.0.1 DONE}
		reap-1.10.1.jar Reap Mod {reap@1.10.1 DONE}
		rftoolsbase-1.14-0.0.3-alpha.jar RFToolsBase {rftoolsbase@NONE DONE}
		rftoolspower-1.14-1.2.3-alpha.jar RFToolsPower {rftoolspower@NONE DONE}
		RingOfAttraction-1.14.4-1.0.12.jar Ring of Attraction {ring_of_attraction@1.0.12 DONE}
		RingOfBlink-1.14.4-1.0.15.jar Ring of Blink {ring_of_blink@1.0.15 DONE}
		RingOfEnderchest-1.14.4-1.0.12.jar Ring of Enderchest {ring_of_enderchest@1.0.12 DONE}
		RingOfGrowth-1.14.4-1.0.13.jar Ring of Growth {ring_of_growth@1.0.13 DONE}
		RingOfMiner-1.14.4-1.0.10.jar Ring of Miner {ring_of_miner@1.0.10 DONE}
		RingOfRepair-1.14.4-1.0.13.jar Ring of Repair {ring_of_repair@1.0.13 DONE}
		RingOfTeleport-1.14.4-1.0.11.jar Ring of Teleport {ring_of_teleport@1.0.11 DONE}
		ruins-1.14.4.1.jar Ruins {ruins@1.14.3.3 DONE}
		SBM-WoodenShears-1.14.4-1.0.0.jar SBM-Wooden Shears {woodenshears@1.0.0 DONE}
		SilentGear-1.14.4-1.3.11+64.jar Silent Gear {silentgear@1.3.11+64 DONE}
		SilentGems-1.14.4-3.4.0+73.jar Silent's Gems 3 {silentgems@3.4.0+73 DONE}
		SilentLib-1.14.4-4.4.0+44.jar Silent Lib {silentlib@4.4.0+44 DONE}
		SimpleDivingGear-3.0.2 mc 1.14.4.jar Simple Diving Gear {simpledivegear@3.0.2 mc 1.14.4 DONE}
		simplefarming-1.14.4-1.1.6.jar Simple Farming {simplefarming@1.14.4-1.1.6 DONE}
		SimpleStorageNetwork-1.14.4-0.0.11.jar Simple Storage Network {storagenetwork@1.14.4-0.0.11 DONE}
		simplylight-0.8.7.jar Simply Light {simplylight@0.8.7 DONE}
		StoneChest-1.14.4-1.0.1.jar Stone Chest {stonechest@1.0.1 DONE}
		StorageDrawers-1.14.4-6.0.4.jar Storage Drawers {storagedrawers@1.14.4-6.0.3 DONE}
		TheVeggieWay-1.14.4-2.0.15.jar The Veggie Way {veggie_way@2.0.15 DONE}
		titanium-1.14.4-2.2.0-d9775a7.jar Titanium {titanium@1.14.4-2.2.0-d9775a7 DONE}
		tombstone-4.1.3-1.14.4.jar Corail Tombstone {tombstone@4.1.3 DONE}
		TorchBandolier-1.14.4-1.3.1+6.jar Torch Bandolier {torchbandolier@1.3.1+6 DONE}
		torchmaster-2.0.0.6-alpha.jar Torchmaster {torchmaster@2.0.0.6-alpha DONE}
		torchoptimizer-1.14.4-2.1.6.jar Torch Optimizer {torchoptimizer@1.14.4-2.1.6 DONE}
		travellersboots-1.14.4-1.2.2.jar Traveller's Boots {travellersboots@1.2.2 DONE}
		u_team_core-1.14.4-2.7.0.129.jar U Team Core {uteamcore@2.7.0.129 DONE}
		Uppers-0.1.10.jar Uppers {uppers@0.1.10 DONE}
		upsizer-mc1.14.4-5.0b2.jar Upsizer {upsizer@5.0.0b2 DONE}
		useful_backpacks-1.14.4-1.7.0.34.jar Useful Backpacks {usefulbackpacks@1.7.0.34 DONE}
		valkyrielib-3.0.0.8.jar ValkyrieLib {valkyrielib@3.0.0.8 DONE}
		WaterStrainer-1.14.4-7.0.2.jar Water Strainer {waterstrainer@1.14.4-7.0.2 DONE}
		weapon_craftery-1.14.4-1.0-Beta-4.jar Weapon Craftery {weapon_craftery@1.14.4-1.0-Beta-4 DONE}
		WoolToString-1.14.2-1.0.0.jar WoolToString {wooltostring@1.0.0 DONE}
		XL-Food-Mod-1.14.4-2.1.0.jar XL Food Mod {xlfoodmod@2.1.0 DONE}
		YAMDA-4.0.1.jar YAMDA {yamda@4.0.1 DONE}
		forge-1.14.4-28.1.6-universal.jar Forge {forge@28.1.6 DONE}
		forge-1.14.4-28.1.6-client.jar Minecraft {minecraft@1.14.4 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['raziel23x'/557, l='Raziel23x World', x=146.56, y=39.00, z=111.86]]
	Data Packs: vanilla, mod:yamda, mod:xlfoodmod, mod:wooltostring, mod:woodenshears, mod:weapon_craftery, mod:waterstrainer, mod:waila, mod:voxelmap, mod:veggie_way, mod:valkyrielib, mod:uteamcore, mod:usefulbackpacks, mod:upsizer, mod:uppers, mod:travellersboots, mod:torchoptimizer, mod:torchmaster, mod:torchbowmod, mod:torchbandolier, mod:tombstone, mod:titanium (incompatible), mod:storagenetwork, mod:storagedrawers, mod:stonechest, mod:simplylight, mod:simplefarming, mod:simpledivegear, mod:silentlib, mod:silentgems, mod:silentgear, mod:ruins, mod:ring_of_teleport, mod:ring_of_repair, mod:ring_of_miner, mod:ring_of_growth, mod:ring_of_enderchest, mod:ring_of_blink, mod:ring_of_attraction, mod:rftoolspower, mod:rftoolsbase, mod:reap, mod:randomthings, mod:randompatches, mod:quickteleports, mod:quickhomes, mod:powder_power, mod:portality (incompatible), mod:placebo, mod:pickletweaks, mod:peanutmod, mod:particlefixes, mod:overloaded, mod:oresalleasy, mod:moreprogression, mod:modnametooltip, mod:minicoal2, mod:metalbarrels, mod:mcjtylib, mod:lycanitesmobs, mod:llor, mod:kleeslabs, mod:jei, mod:ironshulkerbox, mod:ironjetpacks, mod:ironchest, mod:inventorysorter, mod:harvest, mod:gobber2, mod:globaldatapack, mod:gemsplusplus, mod:ftbbackups, mod:forge, mod:forbidden_arcanus, mod:fluidtank, mod:flintblock, mod:firstaid, mod:fastleafdecay, mod:fastfurnace, mod:fastbench, mod:f2l, mod:extcaves, mod:everlastingabilities, mod:essentials, mod:enviromats, mod:enchxchg, mod:enchdesc, mod:elevatorid, mod:easy_steel, mod:defaultsettings, mod:defaultoptions, mod:dankstorage, mod:d2p, mod:cyclopscore, mod:cyclic, mod:cursedearth, mod:cucumber, mod:craftingtweaks, mod:craftingstation, mod:cosmeticarmorreworked, mod:corail_woodcutter, mod:controlling, mod:container, mod:compressed, mod:compatchedstorage, mod:colytra, mod:clumps, mod:charcoalblock, mod:ceilingtorch, mod:carryon, mod:campfiretorches, mod:caelus, mod:buildinggadgets, mod:biomesoplenty, mod:bambooladders, mod:bambooeverything, mod:attributefix, mod:appleskin, mod:apotheosis, mod:angelring, modpack:Custom_Recipe_Datapack.zip (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by TheRandomLabs** [comment]
Sorry, this doesn't have anything to do with RandomPatches.

The exception is occurring here in `Entity`:
```
/**
  * Returns whether this Entity is on the same team as the given Entity.
  */
public boolean isOnSameTeam(Entity entityIn) {
   return this.isOnScoreboardTeam(entityIn.getTeam());
}
```

I assume `HurtByTargetGoal#alertOthers` is passing `null`.
