### ISSUE TITLE
Failed to transform class: net.minecraft.network.NetHandlerPlayServer

### ISSUE THREAD

**Issue by ghost** [TheRandomLabs/RandomPatches#63]
Hello, I am having issues with my players on slower computers having trouble connecting to my server after updating a few mods. I'm assuming that Ice and Fire may be the culprit here due to [this commit](https://github.com/Alex-the-666/Ice_and_Fire/commit/d3d1f2d66254ebc0bb4eacad4b38458fd19dbc9b)?

Here is the error in the server logs:
```
[20:55:27] [Server thread/ERROR] [randompatches]: Failed to transform class: net.minecraft.network.NetHandlerPlayServer
java.lang.NullPointerException: null
	at org.objectweb.asm.tree.InsnList.insert(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at com.therandomlabs.randompatches.patch.NetHandlerPlayServerPatch.patchProcessVehicleMove(NetHandlerPlayServerPatch.java:236) ~[randompatches-1.12.2-1.18.1.1.jar:?]
	at com.therandomlabs.randompatches.patch.NetHandlerPlayServerPatch.apply(NetHandlerPlayServerPatch.java:30) ~[randompatches-1.12.2-1.18.1.1.jar:?]
	at com.therandomlabs.randompatches.core.RPTransformer.transform(RPTransformer.java:37) [randompatches-1.12.2-1.18.1.1.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) [ASMTransformerWrapper$TransformerWrapper.class:?]
	at org.spongepowered.asm.service.mojang.LegacyTransformerHandle.transformClassBytes(LegacyTransformerHandle.java:71) [SteveKunG's-Lib-1.12.2-1.1.5.jar:?]
	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.applyTransformers(MixinServiceLaunchWrapper.java:388) [SteveKunG's-Lib-1.12.2-1.1.5.jar:?]
	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassBytes(MixinServiceLaunchWrapper.java:352) [SteveKunG's-Lib-1.12.2-1.1.5.jar:?]
	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassNode(MixinServiceLaunchWrapper.java:432) [SteveKunG's-Lib-1.12.2-1.1.5.jar:?]
	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:1676) [SteveKunG's-Lib-1.12.2-1.1.5.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:680) [SteveKunG's-Lib-1.12.2-1.1.5.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:670) [SteveKunG's-Lib-1.12.2-1.1.5.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:267) [SteveKunG's-Lib-1.12.2-1.1.5.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241) [SteveKunG's-Lib-1.12.2-1.1.5.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144) [SteveKunG's-Lib-1.12.2-1.1.5.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:267) [SteveKunG's-Lib-1.12.2-1.1.5.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) [SteveKunG's-Lib-1.12.2-1.1.5.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) [SteveKunG's-Lib-1.12.2-1.1.5.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) [SteveKunG's-Lib-1.12.2-1.1.5.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) [SteveKunG's-Lib-1.12.2-1.1.5.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [SteveKunG's-Lib-1.12.2-1.1.5.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_222]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_222]
	at net.minecraft.entity.EntityTracker.track(EntityTracker.java:227) [ol.class:?]
	at net.minecraftforge.fml.common.registry.EntityRegistry.tryTrackingEntity(EntityRegistry.java:369) [EntityRegistry.class:?]
	at net.minecraft.entity.EntityTracker.track(EntityTracker.java:80) [ol.class:?]
	at net.minecraft.world.ServerWorldEventHandler.onEntityAdded(ServerWorldEventHandler.java:37) [op.class:?]
	at net.minecraft.world.World.onEntityAdded(World.java:1222) [amu.class:?]
	at net.minecraft.world.WorldServer.onEntityAdded(WorldServer.java:1112) [oo.class:?]
	at net.minecraft.world.WorldServer.loadEntities(WorldServer.java:1068) [oo.class:?]
	at net.minecraft.world.chunk.Chunk.onLoad(Chunk.java:860) [axw.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:89) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:135) [on.class:?]
	at net.minecraft.world.World.getChunk(World.java:310) [amu.class:?]
	at net.minecraft.world.World.getChunk(World.java:305) [amu.class:?]
	at net.minecraft.world.World.getTileEntity(World.java:2402) [amu.class:?]
	at codechicken.chunkloader.manager.ChunkLoaderManager$ChunkLoaderOrganiser.revive(ChunkLoaderManager.java:360) [ChunkLoaderManager$ChunkLoaderOrganiser.class:?]
	at codechicken.chunkloader.manager.ChunkLoaderManager$PlayerOrganiser.revive(ChunkLoaderManager.java:390) [ChunkLoaderManager$PlayerOrganiser.class:?]
	at codechicken.chunkloader.manager.ChunkLoaderManager$ChunkLoaderOrganiser.revive(ChunkLoaderManager.java:328) [ChunkLoaderManager$ChunkLoaderOrganiser.class:?]
	at codechicken.chunkloader.manager.ChunkLoaderManager$PlayerOrganiser.revive(ChunkLoaderManager.java:390) [ChunkLoaderManager$PlayerOrganiser.class:?]
	at codechicken.chunkloader.manager.ChunkLoaderManager.processLoaderStates(ChunkLoaderManager.java:693) [ChunkLoaderManager.class:?]
	at codechicken.chunkloader.manager.ChunkLoaderManager.onTickEnd(ChunkLoaderManager.java:670) [ChunkLoaderManager.class:?]
	at codechicken.chunkloader.handler.ChunkLoaderEventHandler.worldTick(ChunkLoaderEventHandler.java:32) [ChunkLoaderEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1673_ChunkLoaderEventHandler_worldTick_WorldTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:776) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

**Comment by CHarrison7** [comment]
Having this issue as well.

" Netty Epoll Server IO #3/ERROR [randompatches]: Failed to transform class: net.minecraft.server.network.NetHandlerLoginServer"
