### ISSUE TITLE
With latest update (1.20.0.0) mining causes server error

### ISSUE THREAD

**Issue by JWTHDYTWA** [TheRandomLabs/RandomPatches#72]
1.20.0.0
Solid blocks mining generates crashlog (with VanillaFix).
[Crashlog itself](https://gist.github.com/Warrock3280/3e27f78dc27f4f1781a405c9c01b1632)

**Comment by kellixon** [comment]
Crash every sec.
------------------
Time: 2019-11-19 21:03:30 MSK
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.therandomlabs.randompatches.hook.PlayerInteractionManagerHook.sendBlockChangePacket(Lnet/minecraft/server/management/PlayerInteractionManager;Lnet/minecraft/util/math/BlockPos;)V
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: com.therandomlabs.randompatches.hook.PlayerInteractionManagerHook.sendBlockChangePacket(Lnet/minecraft/server/management/PlayerInteractionManager;Lnet/minecraft/util/math/BlockPos;)V
    at net.minecraft.server.management.PlayerInteractionManager.onBlockClicked(PlayerInteractionManager.java:222)
    at net.minecraft.network.NetHandlerPlayServer.processPlayerDigging(NetHandlerPlayServer.java:693)
    at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:40)
    at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:10)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more

**Comment by xerberus333** [comment]
Mine also has the same NoSuchMethodError in the log:

https://pastebin.com/6wpSR0u3

It's not crashing my game though, even with VanillaFix disabled. Hope this log helps.

I can confirm that the _Mining Ghost Blocks Fix_ config option is what causes the error. I've turned it off for now so as to avoid the fatal error log spam.

**Comment by TheRandomLabs** [comment]
Sorry, I screwed up massively. I'm really not sure how I didn't notice this.
